<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV7Sw5zl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV7Sw5zl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV7Sw5zl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV7Sw5zl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV7Sw5zl\App_KernelDevDebugContainer([
    'container.build_hash' => 'V7Sw5zl',
    'container.build_id' => '355dbe83',
    'container.build_time' => 1661368522,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV7Sw5zl');
